PYTHON_STANDARD_LIBRARIES = ['__future__', '__main__', '_dummy_thread', '_thread', 'abc', 'aifc',
                             'argparse', 'array', 'ast', 'asynchat', 'asyncio', 'asyncore', 'atexit',
                             'audioop', 'base64', 'bdb', 'binascii', 'binhex', 'bisect', 'builtins',
                             'bz2', 'calendar', 'cgi', 'cgitb', 'chunk', 'cmath', 'cmd', 'code',
                             'codecs', 'codeop', 'collections', 'collections.abc', 'colorsys',
                             'compileall', 'concurrent', 'concurrent.futures', 'configparser',
                             'contextlib', 'contextvars', 'copy', 'copyreg', 'cProfile', 'crypt',
                             'csv', 'ctypes', 'curses', 'curses.ascii', 'curses.panel', 'curses.textpad',
                             'dataclasses', 'datetime', 'dbm', 'dbm.dumb', 'dbm.gnu', 'dbm.ndbm', 'decimal',
                             'difflib', 'dis', 'distutils', 'distutils.archive_util', 'distutils.bcppcompiler',
                             'distutils.ccompiler', 'distutils.cmd', 'distutils.command', 'distutils.command.bdist',
                             'distutils.command.bdist_dumb', 'distutils.command.bdist_msi',
                             'distutils.command.bdist_packager', 'distutils.command.bdist_rpm',
                             'distutils.command.bdist_wininst', 'distutils.command.build',
                             'distutils.command.build_clib', 'distutils.command.build_ext',
                             'distutils.command.build_py', 'distutils.command.build_scripts',
                             'distutils.command.check', 'distutils.command.clean', 'distutils.command.config',
                             'distutils.command.install', 'distutils.command.install_data',
                             'distutils.command.install_headers', 'distutils.command.install_lib',
                             'distutils.command.install_scripts', 'distutils.command.register',
                             'distutils.command.sdist', 'distutils.core', 'distutils.cygwinccompiler',
                             'distutils.debug', 'distutils.dep_util', 'distutils.dir_util', 'distutils.dist',
                             'distutils.errors', 'distutils.extension', 'distutils.fancy_getopt',
                             'distutils.file_util', 'distutils.filelist', 'distutils.log', 'distutils.msvccompiler',
                             'distutils.spawn', 'distutils.sysconfig', 'distutils.text_file',
                             'distutils.unixccompiler', 'distutils.util', 'distutils.version', 'doctest',
                             'dummy_threading', 'email', 'email.charset', 'email.contentmanager', 'email.encoders',
                             'email.errors', 'email.generator', 'email.header', 'email.headerregistry',
                             'email.iterators', 'email.message', 'email.mime', 'email.parser', 'email.policy',
                             'email.utils', 'encodings', 'encodings.idna', 'encodings.mbcs', 'encodings.utf_8_sig',
                             'ensurepip', 'enum', 'errno', 'faulthandler', 'fcntl', 'filecmp', 'fileinput',
                             'fnmatch', 'formatter', 'fractions', 'ftplib', 'functools', 'gc', 'getopt', 'getpass',
                             'gettext', 'glob', 'grp', 'gzip', 'hashlib', 'heapq', 'hmac', 'html', 'html.entities',
                             'html.parser', 'http', 'http.client', 'http.cookiejar', 'http.cookies', 'http.server',
                             'imaplib', 'imghdr', 'imp', 'importlib', 'importlib.abc', 'importlib.machinery',
                             'importlib.metadata', 'importlib.resources', 'importlib.util', 'inspect', 'io',
                             'ipaddress', 'itertools', 'json', 'json.tool', 'keyword', 'lib2to3', 'linecache',
                             'locale', 'logging', 'logging.config', 'logging.handlers', 'lzma', 'mailbox', 'mailcap',
                             'marshal', 'math', 'mimetypes', 'mmap', 'modulefinder', 'msilib', 'msvcrt',
                             'multiprocessing', 'multiprocessing.connection', 'multiprocessing.dummy',
                             'multiprocessing.managers', 'multiprocessing.pool', 'multiprocessing.shared_memory',
                             'multiprocessing.sharedctypes', 'netrc', 'nis', 'nntplib', 'numbers', 'operator',
                             'optparse', 'os', 'os.path', 'ossaudiodev', 'parser', 'pathlib', 'pdb', 'pickle',
                             'pickletools', 'pipes', 'pkgutil', 'platform', 'plistlib', 'poplib', 'posix', 'pprint',
                             'profile', 'pstats', 'pty', 'pwd', 'py_compile', 'pyclbr', 'pydoc', 'queue', 'quopri',
                             'random', 're', 'readline', 'reprlib', 'resource', 'rlcompleter', 'runpy', 'sched',
                             'secrets', 'select', 'selectors', 'shelve', 'shlex', 'shutil', 'signal', 'site', 'smtpd',
                             'smtplib', 'sndhdr', 'socket', 'socketserver', 'spwd', 'sqlite3', 'ssl', 'stat',
                             'statistics', 'string', 'stringprep', 'struct', 'subprocess', 'sunau', 'symbol',
                             'symtable', 'sys', 'sysconfig', 'syslog', 'tabnanny', 'tarfile', 'telnetlib', 'tempfile',
                             'termios', 'test', 'test.support', 'test.support.script_helper', 'textwrap', 'threading',
                             'time', 'timeit', 'tkinter', 'tkinter.scrolledtext', 'tkinter.tix', 'tkinter.ttk',
                             'token', 'tokenize', 'trace', 'traceback', 'tracemalloc', 'tty', 'turtle', 'turtledemo',
                             'types', 'typing', 'unicodedata', 'unittest', 'unittest.mock', 'urllib', 'urllib.error',
                             'urllib.parse', 'urllib.request', 'urllib.response', 'urllib.robotparser', 'uu', 'uuid',
                             'venv', 'warnings', 'wave', 'weakref', 'webbrowser', 'winreg', 'winsound', 'wsgiref',
                             'wsgiref.handlers', 'wsgiref.headers', 'wsgiref.simple_server', 'wsgiref.util',
                             'wsgiref.validate', 'xdrlib', 'xml', 'xml.dom', 'xml.dom.minidom', 'xml.dom.pulldom',
                             'xml.etree.ElementTree', 'xml.parsers.expat', 'xml.parsers.expat.errors',
                             'xml.parsers.expat.model', 'xml.sax', 'xml.sax.handler', 'xml.sax.saxutils',
                             'xml.sax.xmlreader', 'xmlrpc', 'xmlrpc.client', 'xmlrpc.server', 'zipapp', 'zipfile',
                             'zipimport', 'zlib', 'graphlib', 'test.support.bytecode_helper',
                             'test.support.socket_helper', 'tkinter.colorchooser', 'tkinter.commondialog',
                             'tkinter.dnd', 'tkinter.filedialog', 'tkinter.font', 'tkinter.messagebox',
                             'tkinter.simpledialog', 'zoneinfo', 'macpath', 'fpectl', '__builtin__', '_winreg',
                             'aepack', 'aetools', 'aetypes', 'al', 'AL', 'anydbm', 'applesingle', 'autoGIL',
                             'BaseHTTPServer', 'Bastion', 'bsddb', 'buildtools', 'Carbon', 'Carbon.AE', 'Carbon.AH',
                             'Carbon.App', 'Carbon.Appearance', 'Carbon.CarbonEvents', 'Carbon.CarbonEvt', 'Carbon.CF',
                             'Carbon.CG', 'Carbon.Cm', 'Carbon.Components', 'Carbon.ControlAccessor',
                             'Carbon.Controls', 'Carbon.CoreFounation', 'Carbon.CoreGraphics', 'Carbon.Ctl',
                             'Carbon.Dialogs', 'Carbon.Dlg', 'Carbon.Drag', 'Carbon.Dragconst', 'Carbon.Events',
                             'Carbon.Evt', 'Carbon.File', 'Carbon.Files', 'Carbon.Fm', 'Carbon.Folder',
                             'Carbon.Folders', 'Carbon.Fonts', 'Carbon.Help', 'Carbon.IBCarbon',
                             'Carbon.IBCarbonRuntime', 'Carbon.Icns', 'Carbon.Icons', 'Carbon.Launch',
                             'Carbon.LaunchServices', 'Carbon.List', 'Carbon.Lists', 'Carbon.MacHelp',
                             'Carbon.MediaDescr', 'Carbon.Menu', 'Carbon.Menus', 'Carbon.Mlte', 'Carbon.OSA',
                             'Carbon.OSAconst', 'Carbon.Qd', 'Carbon.Qdoffs', 'Carbon.QDOffscreen', 'Carbon.Qt',
                             'Carbon.QuickDraw', 'Carbon.QuickTime', 'Carbon.Res', 'Carbon.Resources', 'Carbon.Scrap',
                             'Carbon.Snd', 'Carbon.Sound', 'Carbon.TE', 'Carbon.TextEdit', 'Carbon.Win',
                             'Carbon.Windows', 'cd', 'cfmfile', 'CGIHTTPServer', 'ColorPicker', 'commands',
                             'compiler', 'compiler.ast', 'compiler.visitor', 'ConfigParser', 'Cookie', 'cookielib',
                             'copy_reg', 'cPickle', 'cStringIO', 'dbhash', 'DEVICE', 'dircache',
                             'distutils.emxccompiler', 'dl', 'DocXMLRPCServer', 'dumbdbm', 'dummy_thread',
                             'EasyDialogs', 'exceptions', 'findertools', 'fl', 'FL', 'flp', 'fm', 'fpformat',
                             'FrameWork', 'future_builtins', 'gdbm', 'gensuitemodule', 'gl', 'GL', 'hotshot',
                             'hotshot.stats', 'htmlentitydefs', 'htmllib', 'HTMLParser', 'httplib', 'ic', 'icopen',
                             'imageop', 'imgfile', 'imputil', 'jpeg', 'macerrors', 'MacOS', 'macostools',
                             'macresource', 'md5', 'mhlib', 'mimetools', 'MimeWriter', 'mimify', 'MiniAEFrame',
                             'multifile', 'mutex', 'Nav', 'new', 'PixMapWrapper', 'popen2', 'posixfile', 'Queue',
                             'rexec', 'rfc822', 'robotparser', 'ScrolledText', 'sets', 'sgmllib', 'sha',
                             'SimpleHTTPServer', 'SimpleXMLRPCServer', 'SocketServer', 'statvfs', 'StringIO',
                             'sunaudiodev', 'SUNAUDIODEV', 'thread', 'Tix', 'Tkinter', 'ttk', 'urllib2', 'urlparse',
                             'user', 'UserDict', 'UserList', 'UserString', 'videoreader', 'W', 'whichdb', 'xmlrpclib',
                             'dateutil']
